# MySQL configuration
host: 127.0.0.1
port: 3306
username: root
password: password
database: auth
table: auth_users

# Auth configuration
session_timeout: 300
kick_after_auth_messages: 5
auth_message_cooldown: 10
kick_after_unsuccessful_login_attempts: 3
rejoin_after_unsuccessful_login_attempts_cooldown: 60
allowed_commands_before_login: [login, register, l, reg]
minimum_password_length: 8
maximum_password_length: 16
protection_after_login: 10